apiVersion: apps/v1


kind: Deployment


metadata:
  name: frontend        
  namespace: app-ns         

spec:
  replicas: 2            
  selector:              
    matchLabels:
      app: frontend      

  template:             
    metadata:
      labels:
        app: frontend    

    spec:
      containers:
        - name: frontend                
          image: amandamattosr/frontend-ajuste:latest  
          ports:
            - containerPort: 80          
          env:
            - name: VITE_API_URL         
              value: "http://localhost:5000" 

---

apiVersion: v1


kind: Service

metadata:
  name: frontend         
  namespace: app-ns        

spec:
  ports:
    - port: 80          
  selector:
    app: frontend        
